[metadata]
name = goldi_microcontroller
version = 0.3.0+dev.9045005
author = Johannes Nau
author_email = johannes.nau@tu-ilmenau.de
description = The Crosslab Client Application for the Microcontroller Module
classifiers =
    Programming Language :: Python :: 3
    License :: Other/Proprietary License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8, <3.11

install_requires =
    crosslab_api_client
    crosslab_soa_client
    spi_driver
    crosslab_soa_service_electrical
    crosslab_soa_service_file
    crosslab_soa_service_programming

[options.packages.find]
where = src

[options.package_data]
goldi_microcontroller = [py.typed]

[options.entry_points]
console_scripts =
    crosslab-microcontroller = goldi_microcontroller.__main__:main
