-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.7
-- Thu Mar 23 17:38:29 2023

-- parameterized module component declaration
component PLL_16MHz
    port (CLKI: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_16MHz
    port map (CLKI=>__, CLKOP=>__);
