---
version: '2.1'
services:

# API #############################################################################################
  db:
    image: mariadb
    ports:
      - "3306:3306"
    networks:
      global_default:
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./data:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
  gateway:
    image: gateway-service
    environment:
      - VIRTUAL_HOST=api.$DOMAIN
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.$DOMAIN
      - SERVER_NAME=api.$DOMAIN
      - DEVICE_SERVICE_URL=device.$DOMAIN:8080
      - EXPERIMENT_SERVICE_URL=experiment.$DOMAIN:8080
      - FEDERATION_SERVICE_URL=federation.$DOMAIN:8080
      - AUTH_SERVICE_URL=auth.$DOMAIN:8080
      - UPDATE_SERVICE_URL=update.$DOMAIN:8080
    networks:
      global_default:
    restart: on-failure
  auth:
    hostname: auth.$DOMAIN
    image: auth-service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: $AUTH_DB_USERNAME
      DB_PASSWORD: $AUTH_DB_PASSWORD
      DB_NAME: $AUTH_DB_NAME
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
      BASE_URL: https://api.$DOMAIN
      JWKS_URL: https://api.$DOMAIN/.well-known/jwks.json
      API_TOKEN: $AUTH_API_KEY
      ALLOWLIST: $AUTH_API_KEY:local:authservice,$DEVICE_API_KEY:local:deviceservice,$EXPERIMENT_API_KEY:local:experimentservice,$FEDERATION_API_KEY:local:federationservice,$UPDATE_API_KEY:local:updateservice
    volumes:
      - auth_db:/app/db
    networks:
      global_default:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  device:
    hostname: device.$DOMAIN
    image: device-service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: $DEVICE_DB_USERNAME
      DB_PASSWORD: $DEVICE_DB_PASSWORD
      DB_NAME: $DEVICE_DB_NAME
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
      BASE_URL: https://api.$DOMAIN
      JWKS_URL: https://api.$DOMAIN/.well-known/jwks.json
      API_TOKEN: $DEVICE_API_KEY
    volumes:
      - device_db:/app/db
    networks:
      global_default:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  experiment:
    hostname: experiment.$DOMAIN
    image: experiment-service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: $EXPERIMENT_DB_USERNAME
      DB_PASSWORD: $EXPERIMENT_DB_PASSWORD
      DB_NAME: $EXPERIMENT_DB_NAME
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
      BASE_URL: https://api.$DOMAIN
      JWKS_URL: https://api.$DOMAIN/.well-known/jwks.json
      API_TOKEN: $EXPERIMENT_API_KEY
    volumes:
      - experiment_db:/app/db
    networks:
      global_default:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  federation:
    hostname: federation.$DOMAIN
    image: federation-service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: $FEDERATION_DB_USERNAME
      DB_PASSWORD: $FEDERATION_DB_PASSWORD
      DB_NAME: $FEDERATION_DB_NAME
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
      BASE_URL: https://api.$DOMAIN
      JWKS_URL: https://api.$DOMAIN/.well-known/jwks.json
      API_TOKEN: $FEDERATION_API_KEY
    volumes:
      - federation_db:/app/db
    networks:
      global_default:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  update:
    hostname: update.$DOMAIN
    image: update-service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: $UPDATE_DB_USERNAME
      DB_PASSWORD: $UPDATE_DB_PASSWORD
      DB_NAME: $UPDATE_DB_NAME
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
      BASE_URL: https://api.$DOMAIN
      JWKS_URL: https://api.$DOMAIN/.well-known/jwks.json
      API_TOKEN: $UPDATE_API_KEY
    volumes:
      - update_db:/app/db
    networks:
      global_default:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

# Frontend ########################################################################################
  frontend:
    image: frontend
    environment:
      - GOLDI_API_URL=https://api.$DOMAIN
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=8080
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=www.$DOMAIN
    networks:
      global_default:
    restart: on-failure

  esp:
    image: esp
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/esp
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=www.$DOMAIN
    networks:
      global_default:
    restart: on-failure

  ecp:
    image: ecp
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/ecp
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=www.$DOMAIN
    networks:
      global_default:
    restart: on-failure
  
  gift:
    image: goldi2/gift
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/gift
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=www.$DOMAIN
    networks:
      global_default:
    restart: on-failure

  sane:
    image: goldi2/sane
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/SANE
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=www.$DOMAIN
      - BASE_PATH=/SANE/
    networks:
      global_default:
    restart: on-failure

  beast:
    image: goldi2/beast
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/BEAST
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=www.$DOMAIN
    networks:
      global_default:
    restart: on-failure

  wide-server:
    image: goldi2/wide-server
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=8080
      - VIRTUAL_PATH=/wide/
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=www.$DOMAIN
    networks:
      global_default:
    restart: on-failure

networks:
  global_default:
    external: true

volumes:
  auth_db:
  device_db:
  experiment_db:
  federation_db:
  update_db: