variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build-environment
  - build

default:
  before_script:
    - sudo chown -R $(whoami) .
    - mkdir -p ~/.ssh/ && cp "$CI_SSH_KEY" ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - mkdir -p ./helper/goldi-development-container/licenses && cp "$LATTICE_LICENSE" ./helper/goldi-development-container/licenses/lattice.dat
    - cp "$LOCAL_YML" ./hardware/os/local.yml
    - cp "$DEV_CRT" ./hardware/os/signing.crt.pem
    - cp "$DEV_KEY" ./hardware/os/signing.key.pem
    - /usr/local/share/docker-init.sh

.default_rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG==null'
      variables:
        BRANCH: $CI_COMMIT_BRANCH
        RELEASE: ''
#   - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG!=null'
#     variables:
#       PIPELINE_NAME: 'Branch pipeline: $CI_COMMIT_BRANCH'
#       BRANCH: CI_COMMIT_TAG
#       RELEASE: '--release'

build:
  image: goldi2/devcontainer:latest
  rules:
    - !reference [.default_rules]
    - if : '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
  stage: build
  script:
    - ./scripts/ci.sh --upload --branch $BRANCH --skip-tag daily --skip-tag weekly $RELEASE

build-weekly:
  timeout: 72h
  image: goldi2/devcontainer:latest
  rules:
    - if : '$CI_PIPELINE_SOURCE == "schedule" && $CI_SCHEDULE == "weekly"'
      when: always
      variables:
        BRANCH: $CI_COMMIT_BRANCH
        RELEASE: ''
  stage: build
  script:
    - ./scripts/ci.sh --upload --branch $BRANCH --weekly $RELEASE
