helper/tsdoc-theme-build:
  image: node:latest
  stage: build
  script:
    - cd helper/tsdoc-theme
    - ./scripts/build.sh
    - cd "$CI_BUILDS_DIR" && ./scripts/check_no_changes.sh

helper/openapi-codegeneration-build:
  image: node:latest
  stage: build
  script:
    - cd helper/openapi-codegeneration
    - ./scripts/build.sh
    - cd "$CI_BUILDS_DIR" && ./scripts/check_no_changes.sh

helper/crosslab-typescript-addon-build:
  image: node:latest
  stage: build
  needs:
    - helper/openapi-codegeneration-build
  script:
    - cd helper/crosslab-typescript-addon
    - ./scripts/build.sh
    - cd "$CI_BUILDS_DIR" && ./scripts/check_no_changes.sh

hardware/os-rebuild-world:
  image: ghcr.io/siemens/kas/kas
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  timeout: 48h
  script:
    - cd hardware/os
    - mkdir -p ~/.ssh/ && cp "$CI_SSH_KEY" ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cp "$LOCAL_YML_NO_CACHE" local.yml && cp "$DEV_CRT" signing.crt.pem && cp "$DEV_KEY" signing.key.pem
    - ./scripts/build.sh -c -w --run_on_host
    - ./scripts/sync_sstate.sh -c
    - cd "$CI_BUILDS_DIR" && ./scripts/check_no_changes.sh