variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: crosslab/development-container

stages:
  - generate
  - run

generate-pipeline:
  stage: generate
  script: ./scripts/generate_gitlab_ci.py
  artifacts:
    paths:
      - generated.gitlab-ci.yml

run-pipeline:
  stage: run
  trigger:
    include:
      - artifact: generated.gitlab-ci.yml
        job: generate-pipeline