variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: crosslab/development-container

default:
  before_script:
    - mkdir -p ~/.ssh/ && cp "$CI_SSH_KEY" ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cd "$PROJECT_DIR"
  after_script:
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/upload_badges.sh $CI_JOB_STATUS

.build:
  script:
    - wget https://img.shields.io/badge/build-passing-success?style=flat-square -O "badge_${CI_JOB_NAME}_success.svg"
    - wget https://img.shields.io/badge/build-failed-critica?style=flat-square -O "badge_${CI_JOB_NAME}_failed.svg"
    - ./scripts/build.sh $BUILD_PARAMETERS
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh
  artifacts:
    paths:
      - $PROJECT_DIR/dist

.build-spec:
  extends: .build-node
  variables:
    BUILD_PARAMETERS: -s
    
.lint:
  script:
    - wget https://img.shields.io/badge/linting-passing-success?style=flat-square -O "badge_${CI_JOB_NAME}_success.svg"
    - wget https://img.shields.io/badge/linting-failed-critica?style=flat-square -O "badge_${CI_JOB_NAME}_failed.svg"
    - ./scripts/lint.sh

.test:
  script:
    - wget https://img.shields.io/badge/tests-passing-success?style=flat-square -O "badge_${CI_JOB_NAME}_success.svg"
    - wget https://img.shields.io/badge/tests-failed-critica?style=flat-square -O "badge_${CI_JOB_NAME}_failed.svg"
    - ./scripts/test.sh

.test-python:
  extends: .test-node
################################################################################
# Helper #######################################################################
################################################################################
helper/tsdoc-theme-build:
  extends: .build
  variables:
    PROJECT_DIR: helper/tsdoc-theme
  needs: []
  dependencies: []

helper/openapi-codegeneration-build:
  extends: .build
  variables:
    PROJECT_DIR: helper/openapi-codegeneration
  needs: []
  dependencies: []

helper/crosslab-typescript-addon-build:
  extends: .build
  variables:
    PROJECT_DIR: helper/crosslab-typescript-addon
  needs:
    - job: helper/openapi-codegeneration-build
      optional: true
      artifacts: true


################################################################################
# Backend ######################################################################
################################################################################

backend-services/auth-build-spec:
  extends: .build-spec
  variables:
    PROJECT_DIR: backend-services/auth
  needs: []
  dependencies: []

backend-services/auth-lint:
  extends: .lint
  variables:
    PROJECT_DIR: backend-services/auth
  needs:
    - job: backend-services/auth-build-spec
      optional: true
      artifacts: true


backend-services/booking-build-spec:
  extends: .build-spec
  variables:
    PROJECT_DIR: backend-services/booking
  needs: []
  dependencies: []

backend-services/booking-lint:
  extends: .lint
  variables:
    PROJECT_DIR: backend-services/booking
  needs:
    - job: backend-services/booking-build-spec
      optional: true
      artifacts: true


backend-services/device-build-spec:
  extends: .build-spec
  variables:
    PROJECT_DIR: backend-services/device
  needs: []
  dependencies: []

backend-services/device-lint:
  extends: .lint
  variables:
    PROJECT_DIR: backend-services/device
  needs:
    - job: backend-services/device-build-spec
      optional: true
      artifacts: true


backend-services/experiment-build-spec:
  extends: .build-spec
  variables:
    PROJECT_DIR: backend-services/experiment
  needs: []
  dependencies: []

backend-services/experiment-lint:
  extends: .lint
  variables:
    PROJECT_DIR: backend-services/experiment
  needs:
    - job: backend-services/experiment-build-spec
      optional: true
      artifacts: true


backend-services/federation-build-spec:
  extends: .build-spec
  variables:
    PROJECT_DIR: backend-services/federation
  needs: []
  dependencies: []

backend-services/federation-lint:
  extends: .lint
  variables:
    PROJECT_DIR: backend-services/federation
  needs:
    - job: backend-services/federation-build-spec
      optional: true
      artifacts: true


backend-services/update-build-spec:
  extends: .build-spec
  variables:
    PROJECT_DIR: backend-services/update
  needs: []
  dependencies: []

backend-services/update-lint:
  extends: .lint
  variables:
    PROJECT_DIR: backend-services/update
  needs:
    - job: backend-services/update-build-spec
      optional: true
      artifacts: true



backend-services/openapi-build-spec:
  extends: .build-spec
  variables:
    PROJECT_DIR: backend-services/openapi
  needs:
    - job: backend-services/auth-build-spec
      optional: true
      artifacts: true
    - job: backend-services/booking-build-spec
      optional: true
      artifacts: true
    - job: backend-services/device-build-spec
      optional: true
      artifacts: true
    - job: backend-services/experiment-build-spec
      optional: true
      artifacts: true
    - job: backend-services/federation-build-spec
      optional: true
      artifacts: true
    - job: backend-services/update-build-spec
      optional: true
      artifacts: true

backend-services/openapi-lint:
  extends: .lint
  variables:
    PROJECT_DIR: backend-services/openapi
  needs:
    - job: backend-services/openapi-build-spec
      optional: true
      artifacts: true
    - job: backend-services/auth-lint
      optional: true
      artifacts: true
    - job: backend-services/booking-lint
      optional: true
      artifacts: true
    - job: backend-services/device-lint
      optional: true
      artifacts: true
    - job: backend-services/experiment-lint
      optional: true
      artifacts: true
    - job: backend-services/federation-lint
      optional: true
      artifacts: true
    - job: backend-services/update-lint
      optional: true
      artifacts: true


################################################################################
# Clients ######################################################################
################################################################################
clients/api/js-build:
  extends: .build
  variables:
    PROJECT_DIR: clients/api/js
  needs:
    - job: backend-services/auth-build-spec
      optional: true
      artifacts: true
    - job: backend-services/booking-build-spec
      optional: true
      artifacts: true
    - job: backend-services/device-build-spec
      optional: true
      artifacts: true
    - job: backend-services/experiment-build-spec
      optional: true
      artifacts: true
    - job: backend-services/federation-build-spec
      optional: true
      artifacts: true
    - job: backend-services/update-build-spec
      optional: true
      artifacts: true
    - job: helper/crosslab-typescript-addon-build
      optional: true
      artifacts: true
    - job: helper/tsdoc-theme-build
      optional: true
      artifacts: true
    - job: helper/openapi-codegeneration-build
      optional: true
      artifacts: true


clients/api/python-build:
  extends: .build
  variables:
    PROJECT_DIR: clients/api/python
  needs:
    - job: backend-services/openapi-build-spec
      optional: true
      artifacts: true
    - job: helper/openapi-codegeneration-build
      optional: true
      artifacts: true

clients/api/python-lint:
  extends: .lint
  variables:
    PROJECT_DIR: clients/api/python
  needs:
    - job: clients/api/python-build
      optional: true
      artifacts: true

clients/api/python-test:
  extends: .test
  variables:
    PROJECT_DIR: clients/api/python
  needs:
    - job: clients/api/python-build
      optional: true
      artifacts: true


clients/soa/python-build:
  extends: .build
  variables:
    PROJECT_DIR: clients/soa/python
  needs:
    - job: backend-services/openapi-build-spec
      optional: true
      artifacts: true
    - job: helper/openapi-codegeneration-build
      optional: true
      artifacts: true
    - job: clients/api/python-test
      optional: true
      artifacts: true

clients/soa/python-lint:
  extends: .lint
  variables:
    PROJECT_DIR: clients/soa/python
  needs:
    - job: clients/soa/python-build
      optional: true
      artifacts: true

clients/soa/python-test:
  extends: .test
  variables:
    PROJECT_DIR: clients/soa/python
  needs:
    - job: clients/soa/python-build
      optional: true
      artifacts: true

################################################################################
# Hardware #####################################################################
################################################################################
hardware/os-rebuild-world:
  image: ghcr.io/siemens/kas/kas
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  timeout: 48h
  script:
    - cd hardware/os
    - mkdir -p ~/.ssh/ && cp "$CI_SSH_KEY" ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cp "$LOCAL_YML_NO_CACHE" local.yml && cp "$DEV_CRT" signing.crt.pem && cp "$DEV_KEY" signing.key.pem
    - ./scripts/build.sh -c -w --run_on_host
    - ./scripts/sync_sstate.sh -c
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh
