variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: crosslab/development-container

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"

stages:
  - generate
  - run

generate-pipeline:
  stage: generate
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        GENERATE_OPTIONS: "--static"
    - if: $CI_PIPELINE_SOURCE == "web"
      variables:
        GENERATE_OPTIONS: "--static"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      variables:
        GENERATE_OPTIONS: "--static"
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
      - git config --global --add safe.directory '*'
      - ./scripts/generate_gitlab_ci.py --last-commit=${CI_COMMIT_BEFORE_SHA} --this-commit=${CI_COMMIT_SHA} $GENERATE_OPTIONS
  artifacts:
    paths:
      - generated.gitlab-ci.yml

run-pipeline:
  stage: run
  trigger:
    include:
      - artifact: generated.gitlab-ci.yml
        job: generate-pipeline
    strategy: depend
