variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - lint
  - test
  
.build-node:
  image: node:latest
  stage: build
  script:
    - cd "$PROJECT_DIR"
    - ./scripts/build.sh $BUILD_PARAMETERS
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh
  artifacts:
    paths:
      - $PROJECT_DIR/dist

.build-spec-node:
  extends: .build-node
  variables:
    BUILD_PARAMETERS: -s

.build-python:
  extends: .build-node
  image: nikolaik/python-nodejs
    
.lint-node:
  image: node:latest
  stage: lint
  script:
    - cd "$PROJECT_DIR"
    - ./scripts/lint.sh

################################################################################
# Helper #######################################################################
################################################################################
helper/tsdoc-theme-build:
  extends: .build-node
  variables:
    PROJECT_DIR: helper/tsdoc-theme
  needs: []
  dependencies: []
  rules:
    - changes:
      - crosslab/helper/tsdoc-theme/*
      - crosslab/helper/tsdoc-theme/**/*

helper/openapi-codegeneration-build:
  extends: .build-node
  variables:
    PROJECT_DIR: helper/openapi-codegeneration
  needs: []
  dependencies: []
  rules:
    - changes:
      - crosslab/helper/openapi-codegeneration/*
      - crosslab/helper/openapi-codegeneration/**/*

helper/crosslab-typescript-addon-build:
  extends: .build-node
  variables:
    PROJECT_DIR: helper/crosslab-typescript-addon
  needs:
    - job: helper/openapi-codegeneration-build
      optional: true
      artifacts: false
  dependencies: []
  before_script:
    - apt update && apt install -y unzip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=helper/openapi-codegeneration-build&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
  rules:
    - changes:
      - crosslab/helper/crosslab-typescript-addon/*
      - crosslab/helper/crosslab-typescript-addon/**/*
      - crosslab/helper/openapi-codegeneration/*
      - crosslab/helper/openapi-codegeneration/**/*


################################################################################
# Backend ######################################################################
################################################################################

backend-services/auth-build-spec:
  extends: .build-spec-node
  variables:
    PROJECT_DIR: backend-services/auth
  needs: []
  dependencies: []
  rules:
    - changes:
      - crosslab/services/auth/*
      - crosslab/services/auth/**/*

backend-services/booking-build-spec:
  extends: .build-spec-node
  variables:
    PROJECT_DIR: backend-services/booking
  needs: []
  dependencies: []
  rules:
    - changes:
      - crosslab/services/booking/*
      - crosslab/services/booking/**/*

backend-services/device-build-spec:
  extends: .build-spec-node
  variables:
    PROJECT_DIR: backend-services/device
  needs: []
  dependencies: []
  rules:
    - changes:
      - crosslab/services/device/*
      - crosslab/services/device/**/*

backend-services/experiment-build-spec:
  extends: .build-spec-node
  variables:
    PROJECT_DIR: backend-services/experiment
  needs: []
  dependencies: []
  rules:
    - changes:
      - crosslab/services/experiment/*
      - crosslab/services/experiment/**/*

backend-services/federation-build-spec:
  extends: .build-spec-node
  variables:
    PROJECT_DIR: backend-services/federation
  needs: []
  dependencies: []
  rules:
    - changes:
      - crosslab/services/federation/*
      - crosslab/services/federation/**/*

backend-services/update-build-spec:
  extends: .build-spec-node
  variables:
    PROJECT_DIR: backend-services/update
  needs: []
  dependencies: []
  rules:
    - changes:
      - crosslab/services/update/*
      - crosslab/services/update/**/*


backend-services/openapi-build-spec:
  extends: .build-spec-node
  variables:
    PROJECT_DIR: backend-services/openapi
  needs:
    - job: backend-services/auth-build-spec
      optional: true
      artifacts: false
    - job: backend-services/booking-build-spec
      optional: true
      artifacts: false
    - job: backend-services/device-build-spec
      optional: true
      artifacts: false
    - job: backend-services/experiment-build-spec
      optional: true
      artifacts: false
    - job: backend-services/federation-build-spec
      optional: true
      artifacts: false
    - job: backend-services/update-build-spec
      optional: true
      artifacts: false
  dependencies: []
  before_script:
    - apt update && apt install -y unzip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/auth-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/booking-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/device-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/experiment-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/federation-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/update-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
  rules:
    - changes:
      - crosslab/services/auth/*
      - crosslab/services/auth/**/*
      - crosslab/services/booking/*
      - crosslab/services/booking/**/*
      - crosslab/services/device/*
      - crosslab/services/device/**/*
      - crosslab/services/experiment/*
      - crosslab/services/experiment/**/*
      - crosslab/services/federation/*
      - crosslab/services/federation/**/*
      - crosslab/services/openapi/*
      - crosslab/services/openapi/**/*
      - crosslab/services/update/*
      - crosslab/services/update/**/*

backend-services/openapi-lint:
  extends: .lint-node
  variables:
    PROJECT_DIR: backend-services/openapi
  needs:
    - job: backend-services/openapi-build-spec
      optional: true
      artifacts: false
  dependencies: []
  before_script:
    - apt update && apt install -y unzip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/openapi-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
  rules:
    - changes:
      - crosslab/services/auth/*
      - crosslab/services/auth/**/*
      - crosslab/services/booking/*
      - crosslab/services/booking/**/*
      - crosslab/services/device/*
      - crosslab/services/device/**/*
      - crosslab/services/experiment/*
      - crosslab/services/experiment/**/*
      - crosslab/services/federation/*
      - crosslab/services/federation/**/*
      - crosslab/services/openapi/*
      - crosslab/services/openapi/**/*
      - crosslab/services/update/*
      - crosslab/services/update/**/*


################################################################################
# Clients ######################################################################
################################################################################
clients/api/js-build:
  extends: .build-node
  variables:
    PROJECT_DIR: clients/api/js
  needs:
    - job: backend-services/auth-build-spec
      optional: true
      artifacts: false
    - job: backend-services/booking-build-spec
      optional: true
      artifacts: false
    - job: backend-services/device-build-spec
      optional: true
      artifacts: false
    - job: backend-services/experiment-build-spec
      optional: true
      artifacts: false
    - job: backend-services/federation-build-spec
      optional: true
      artifacts: false
    - job: backend-services/update-build-spec
      optional: true
      artifacts: false
    - job: helper/crosslab-typescript-addon-build
      optional: true
      artifacts: false
    - job: helper/tsdoc-theme-build
      optional: true
      artifacts: false
    - job: helper/openapi-codegeneration-build
      optional: true
      artifacts: false
  dependencies: []
  before_script:
    - apt update && apt install -y unzip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/auth-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/booking-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/device-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/experiment-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/federation-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/update-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=helper/crosslab-typescript-addon-build&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=helper/tsdoc-theme-build&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=helper/openapi-codegeneration-build&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
  rules:
    - changes:
      - crosslab/clients/api/js/*
      - crosslab/clients/api/js/**/*
      - crosslab/helper/crosslab-typescript-addon/*
      - crosslab/helper/crosslab-typescript-addon/**/*
      - crosslab/helper/openapi-codegeneration/*
      - crosslab/helper/openapi-codegeneration/**/*
      - crosslab/helper/tsdoc-theme/*
      - crosslab/helper/tsdoc-theme/**/*
      - crosslab/services/auth/*
      - crosslab/services/auth/**/*
      - crosslab/services/booking/*
      - crosslab/services/booking/**/*
      - crosslab/services/device/*
      - crosslab/services/device/**/*
      - crosslab/services/experiment/*
      - crosslab/services/experiment/**/*
      - crosslab/services/federation/*
      - crosslab/services/federation/**/*
      - crosslab/services/update/*
      - crosslab/services/update/**/*


clients/api/python-build:
  extends: .build-python
  variables:
    PROJECT_DIR: clients/api/python
  needs:
    - job: backend-services/openapi-build-spec
      optional: true
      artifacts: false
    - job: helper/openapi-codegeneration-build
      optional: true
      artifacts: false
  dependencies: []
  before_script:
    - apt update && apt install -y unzip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=backend-services/openapi-build-spec&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
    - curl --location --output artifacts.zip "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=helper/openapi-codegeneration-build&job_token=$CI_JOB_TOKEN" && unzip artifacts.zip && rm artifacts.zip
  rules:
    - changes:
      - crosslab/clients/api/python/*
      - crosslab/clients/api/python/**/*
      - crosslab/helper/openapi-codegeneration/*
      - crosslab/helper/openapi-codegeneration/**/*
      - crosslab/services/auth/*
      - crosslab/services/auth/**/*
      - crosslab/services/booking/*
      - crosslab/services/booking/**/*
      - crosslab/services/device/*
      - crosslab/services/device/**/*
      - crosslab/services/experiment/*
      - crosslab/services/experiment/**/*
      - crosslab/services/federation/*
      - crosslab/services/federation/**/*
      - crosslab/services/openapi/*
      - crosslab/services/openapi/**/*
      - crosslab/services/update/*
      - crosslab/services/update/**/*

################################################################################
# Hardware #####################################################################
################################################################################
hardware/os-rebuild-world:
  image: ghcr.io/siemens/kas/kas
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  timeout: 48h
  script:
    - cd hardware/os
    - mkdir -p ~/.ssh/ && cp "$CI_SSH_KEY" ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cp "$LOCAL_YML_NO_CACHE" local.yml && cp "$DEV_CRT" signing.crt.pem && cp "$DEV_KEY" signing.key.pem
    - ./scripts/build.sh -c -w --run_on_host
    - ./scripts/sync_sstate.sh -c
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh
