variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - lint
  - test
  
.build-node:
  image: node:latest
  stage: build
  script:
    - cd "$PROJECT_DIR"
    - ./scripts/build.sh $BUILD_PARAMETERS
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh
  artifacts:
    paths:
      - $PROJECT_DIR/dist

.build-spec-node:
  extends: .build-node
  variables:
    BUILD_PARAMETERS: -s

.build-python:
  extends: .build-node
  image: nikolaik/python-nodejs
    
.lint-node:
  image: node:latest
  stage: lint
  script:
    - cd "$PROJECT_DIR"
    - ./scripts/lint.sh

.lint-python:
  extends: .lint-node
  image: nikolaik/python-nodejs

################################################################################
# Helper #######################################################################
################################################################################
> helper/tsdoc-theme build(node)
> helper/openapi-codegeneration build(node)
> helper/crosslab-typescript-addon build(node) < helper/openapi-codegeneration:build

################################################################################
# Backend ######################################################################
################################################################################

> backend-services/auth build-spec(node)
> backend-services/auth lint(node) < backend-services/auth:build-spec

> backend-services/booking build-spec(node)
> backend-services/booking lint(node) < backend-services/booking:build-spec

> backend-services/device build-spec(node)
> backend-services/device lint(node) < backend-services/device:build-spec

> backend-services/experiment build-spec(node)
> backend-services/experiment lint(node) < backend-services/experiment:build-spec

> backend-services/federation build-spec(node)
> backend-services/federation lint(node) < backend-services/federation:build-spec

> backend-services/update build-spec(node)
> backend-services/update lint(node) < backend-services/update:build-spec


> backend-services/openapi build-spec(node) < backend-services/auth:build-spec backend-services/booking:build-spec backend-services/device:build-spec backend-services/experiment:build-spec backend-services/federation:build-spec backend-services/update:build-spec
> backend-services/openapi lint(node) < backend-services/openapi:build-spec backend-services/auth:lint backend-services/booking:lint backend-services/device:lint backend-services/experiment:lint backend-services/federation:lint backend-services/update:lint

################################################################################
# Clients ######################################################################
################################################################################
> clients/api/js build(node) < backend-services/auth:build-spec backend-services/booking:build-spec backend-services/device:build-spec backend-services/experiment:build-spec backend-services/federation:build-spec backend-services/update:build-spec helper/crosslab-typescript-addon:build helper/tsdoc-theme:build helper/openapi-codegeneration:build

> clients/api/python build(python) < backend-services/openapi:build-spec helper/openapi-codegeneration:build
> clients/api/python lint(python) < clients/api/python:build
################################################################################
# Hardware #####################################################################
################################################################################
hardware/os-rebuild-world:
  image: ghcr.io/siemens/kas/kas
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  timeout: 48h
  script:
    - cd hardware/os
    - mkdir -p ~/.ssh/ && cp "$CI_SSH_KEY" ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cp "$LOCAL_YML_NO_CACHE" local.yml && cp "$DEV_CRT" signing.crt.pem && cp "$DEV_KEY" signing.key.pem
    - ./scripts/build.sh -c -w --run_on_host
    - ./scripts/sync_sstate.sh -c
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh