################################################################################
# Helper #######################################################################
################################################################################
> helper/tsdoc-theme build
> helper/openapi-codegeneration build
> helper/crosslab-typescript-addon build < helper/openapi-codegeneration:build

################################################################################
# Backend ######################################################################
################################################################################

> backend-services/auth build-spec
> backend-services/auth lint < backend-services/auth:build-spec

> backend-services/booking build-spec
> backend-services/booking lint < backend-services/booking:build-spec

> backend-services/device build-spec
> backend-services/device lint < backend-services/device:build-spec

> backend-services/experiment build-spec
> backend-services/experiment lint < backend-services/experiment:build-spec

> backend-services/federation build-spec
> backend-services/federation lint < backend-services/federation:build-spec

> backend-services/update build-spec
> backend-services/update lint < backend-services/update:build-spec


> backend-services/openapi build-spec < backend-services/auth:build-spec backend-services/booking:build-spec backend-services/device:build-spec backend-services/experiment:build-spec backend-services/federation:build-spec backend-services/update:build-spec
> backend-services/openapi lint < backend-services/openapi:build-spec

################################################################################
# Clients ######################################################################
################################################################################
> clients/api/js build < backend-services/auth:build-spec backend-services/booking:build-spec backend-services/device:build-spec backend-services/experiment:build-spec backend-services/federation:build-spec backend-services/update:build-spec helper/crosslab-typescript-addon:build helper/tsdoc-theme:build helper/openapi-codegeneration:build

> clients/api/python build < backend-services/openapi:build-spec helper/openapi-codegeneration:build
> clients/api/python lint < clients/api/python:build
> clients/api/python test < clients/api/python:build

> clients/soa/python build < backend-services/openapi:build-spec helper/openapi-codegeneration:build clients/api/python:build
> clients/soa/python lint < clients/soa/python:build
> clients/soa/python test < clients/soa/python:build

# SOA Service ##################################################################

> clients/soa_services/electricalConnection/python build < helper/openapi-codegeneration:build clients/api/python:build clients/soa/python:build
> clients/soa_services/electricalConnection/python lint < clients/soa_services/electricalConnection/python:build
> clients/soa_services/electricalConnection/python test < clients/soa_services/electricalConnection/python:lint