################################################################################
# Build Development Container ##################################################
################################################################################

helper/goldi-development-container:
  - script: build
    dependencies:
      - crosslab/helper/development-container:build
    tags:
      - environment

################################################################################
# Frontend Services ############################################################
################################################################################

frontend-services/config-tool:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build

frontend-services/experiment-control-panel:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build
      - crosslab/clients/soa_services/webcam/js:build
      - crosslab/clients/soa_services/file/js:build

################################################################################
# Hardware #####################################################################
################################################################################

hardware/common/config-interface:
  - script: build
  - script: lint

hardware/boards/axis_portal_v1/fpga:
  - script: build