################################################################################
# Frontend Services ############################################################
################################################################################

frontend-services/website:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build

# frontend-services/config-tool:
#   - script: build
#     dependencies:
#       - crosslab/clients/api/js:build

frontend-services/edge_devices/experiment-control-panel:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build
      - crosslab/clients/soa_services/webcam/js:build
      - crosslab/clients/soa_services/file/js:build

frontend-services/edge_devices/fsm-interpreter:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build

frontend-services/edge_devices/virtual-pspu:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build

frontend-services/edge_devices/ti-lab-ecp:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build

frontend-services/apitool:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build

frontend-services/gift-3.0:
  - script: build
  - script: build-docker
    dependencies:
      - frontend-services/gift-3.0:build

frontend-services/update:
  - script: build
    dependencies:
      - crosslab/services/common:build
  - script: build-docker
    dependencies:
      - frontend-services/update:build
  - script: lint
    dependencies:
      - frontend-services/update:build
    tags:
      - test

################################################################################
# Hardware #####################################################################
################################################################################

hardware/common/fpga:
  - script: test

hardware/common/config-interface:
  - script: build
  - script: lint
    dependencies:
      - hardware/common/config-interface:build

hardware/common/spi-driver:
  - script: build
  - script: lint
    dependencies:
      - hardware/common/spi-driver:build
  - script: test
    dependencies:
      - hardware/common/spi-driver:build


hardware/boards/axis_portal_v1/fpga:
  - script: build
    dependencies:
      - hardware/common/fpga:test
  - script: test

hardware/boards/axis_portal_v1/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/axis_portal_v1/crosslab:build

hardware/boards/warehouse_v2/fpga:
  - script: build
    dependencies:
      - hardware/common/fpga:test
  - script: test

hardware/boards/warehouse_v2/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/warehouse_v2/crosslab:build

hardware/boards/axis_portal_v2/fpga:
  - script: build
    dependencies:
      - hardware/common/fpga:test
  - script: test

hardware/boards/axis_portal_v2/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/axis_portal_v2/crosslab:build


hardware/boards/mole/fpga:
  - script: build
  - script: test

hardware/boards/mole/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/mole/crosslab:build

hardware/os:
  - script: build_sstate_ipk
    tags:
      - weekly
  - script: build_axis_portal_v1
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/axis_portal_v1/fpga:build
      - hardware/boards/axis_portal_v1/crosslab:build
  - script: build_warehouse_v2
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/warehouse_v2/fpga:build
      - hardware/boards/warehouse_v2/crosslab:build
  - script: build_axis_portal_v2
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/axis_portal_v2/fpga:build
      - hardware/boards/axis_portal_v2/crosslab:build
  - script: build_mole
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/mole/fpga:build
      - hardware/boards/mole/crosslab:build
