################################################################################
# Build Development Container ##################################################
################################################################################

helper/goldi-development-container:
  - script: build
    dependencies:
      - crosslab/helper/development-container:build
    tags:
      - environment

################################################################################
# Frontend Services ############################################################
################################################################################

frontend-services/website:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build

frontend-services/config-tool:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build

frontend-services/experiment-control-panel:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build
      - crosslab/clients/soa_services/webcam/js:build
      - crosslab/clients/soa_services/file/js:build

################################################################################
# Hardware #####################################################################
################################################################################

#hardware/common/fpga:
#  - script: test

hardware/common/config-interface:
  - script: build
  - script: lint
    dependencies:
      - hardware/common/config-interface:build

hardware/common/spi-driver:
  - script: build
  - script: lint
    dependencies:
      - hardware/common/spi-driver:build
  - script: test
    dependencies:
      - hardware/common/spi-driver:build


hardware/boards/axis_portal_v1/fpga:
  - script: build
#  - script: test

hardware/boards/axis_portal_v1/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/axis_portal_v1/crosslab:build

#hardware/boards/axis_portal_v2/fpga:
#  - script: build
#  - script: test

hardware/os:
  - script: build_sstate_ipk
    tags:
      - weekly
  - script: build_axis_portal_v1
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/axis_portal_v1/fpga:build
      - hardware/boards/axis_portal_v1/crosslab:build
    tags:
      - daily
#  - script: build_warehouse
#    dependencies:
#      - hardware/common/config-interface:build
#      - hardware/common/spi-driver:build
#      #- hardware/boards/warehouse/fpga:build
#      #- hardware/boards/warehouse/crosslab:build
#    tags:
#      - daily