################################################################################
# Backend Services #############################################################
################################################################################

backend-services/arduino-cli:
  - script: build
    dependencies:
      - crosslab/helper/abstract-messaging-channel:build
      - crosslab/helper/crosslab-messaging-channel:build
      - crosslab/helper/filesystem-schemas:build
      - crosslab/clients/soa_services/compilation/js:build
      - crosslab/clients/soa/js:build
  - script: build-docker
    dependencies:
      - backend-services/arduino-cli:build

backend-services/arduino-language-server:
  - script: build
    dependencies:
      - crosslab/helper/abstract-messaging-channel:build
      - crosslab/helper/filesystem-schemas:build
      - crosslab/clients/soa_services/lsp/js:build
      - crosslab/clients/soa/js:build
  - script: build-docker
    dependencies:
      - backend-services/arduino-language-server:build

################################################################################
# Frontend Services ############################################################
################################################################################

frontend-services/website:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build

# frontend-services/config-tool:
#   - script: build
#     dependencies:
#       - crosslab/clients/api/js:build

frontend-services/edge_devices/experiment-control-panel:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build
      - crosslab/clients/soa_services/webcam/js:build
      - crosslab/clients/soa_services/file/js:build

frontend-services/edge_devices/fsm-interpreter:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build

frontend-services/edge_devices/virtual-pspu:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build

frontend-services/edge_devices/ti-lab-ecp:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build
      - crosslab/clients/soa/js:build
      - crosslab/clients/soa_services/electricalConnection/js:build

frontend-services/apitool:
  - script: build
    dependencies:
      - crosslab/clients/api/js:build

frontend-services/gift-3.0:
  - script: build
  - script: build-docker
    dependencies:
      - frontend-services/gift-3.0:build

frontend-services/update:
  - script: build
    dependencies:
      - crosslab/services/common:build
  - script: build-docker
    dependencies:
      - frontend-services/update:build
  - script: lint
    dependencies:
      - frontend-services/update:build
    tags:
      - test

frontend-services/cwide:
  - script: copy-extensions
    dependencies:
      - frontend-services/cwide/extensions/base:build
      - frontend-services/cwide/extensions/collaboration:build
      - frontend-services/cwide/extensions/compilation:build
      - frontend-services/cwide/extensions/debugging:build
      - frontend-services/cwide/extensions/filesystem:build
      - frontend-services/cwide/extensions/lsp:build
      - frontend-services/cwide/extensions/testing:build
  - script: build-docker
    dependencies:
      - frontend-services/cwide:copy-extensions

frontend-services/cwide/editor-settings:
  - script: build

frontend-services/cwide/extensions/base:
  - script: build
    dependencies:
      - crosslab/clients/soa/js:build

frontend-services/cwide/extensions/collaboration:
  - script: build
    dependencies:
      - crosslab/clients/soa_services/collaboration/js:build

frontend-services/cwide/extensions/compilation:
  - script: build
    dependencies:
      - crosslab/clients/soa_services/collaboration/js:build
      - crosslab/clients/soa_services/compilation/js:build
      - crosslab/clients/soa_services/filesystem/js:build
      - crosslab/clients/soa_services/programming/js:build

frontend-services/cwide/extensions/debugging:
  - script: build
    dependencies:
      - crosslab/helper/filesystem-schemas:build
      - crosslab/clients/soa_services/collaboration/js:build
      - crosslab/clients/soa_services/debugging-adapter/js:build
      - crosslab/clients/soa_services/filesystem/js:build

frontend-services/cwide/extensions/filesystem:
  - script: build
    dependencies:
      - crosslab/helper/abstract-messaging-channel:build
      - crosslab/helper/filesystem-schemas:build
      - frontend-services/cwide/editor-settings:build
      - crosslab/clients/soa_services/collaboration/js:build
      - crosslab/clients/soa_services/filesystem/js:build

frontend-services/cwide/extensions/lsp:
  - script: build
    dependencies:
      - crosslab/helper/abstract-messaging-channel:build
      - crosslab/helper/filesystem-schemas:build
      - crosslab/clients/soa_services/lsp/js:build

frontend-services/cwide/extensions/testing:
  - script: build
    dependencies:
      - crosslab/clients/soa_services/collaboration/js:build
      - crosslab/clients/soa_services/testing/js:build

################################################################################
# Hardware #####################################################################
################################################################################

hardware/common/fpga:
  - script: test

hardware/common/config-interface:
  - script: build
  - script: lint
    dependencies:
      - hardware/common/config-interface:build

hardware/common/spi-driver:
  - script: build
  - script: lint
    dependencies:
      - hardware/common/spi-driver:build
  - script: test
    dependencies:
      - hardware/common/spi-driver:build


hardware/boards/axis_portal_v1/fpga:
  - script: build
    dependencies:
      - hardware/common/fpga:test
  - script: test

hardware/boards/axis_portal_v1/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/axis_portal_v1/crosslab:build

hardware/boards/warehouse_v2/fpga:
  - script: build
    dependencies:
      - hardware/common/fpga:test
  - script: test

hardware/boards/warehouse_v2/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/warehouse_v2/crosslab:build

hardware/boards/axis_portal_v2/fpga:
  - script: build
    dependencies:
      - hardware/common/fpga:test
  - script: test

hardware/boards/axis_portal_v2/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/axis_portal_v2/crosslab:build


hardware/boards/mole/fpga:
  - script: build
  - script: test

hardware/boards/mole/crosslab:
  - script: build
    dependencies:
      - hardware/common/spi-driver:build
  - script: lint
    dependencies:
      - hardware/boards/mole/crosslab:build

hardware/os:
  - script: build_sstate_ipk
    tags:
      - weekly
  - script: build_axis_portal_v1
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/axis_portal_v1/fpga:build
      - hardware/boards/axis_portal_v1/crosslab:build
  - script: build_warehouse_v2
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/warehouse_v2/fpga:build
      - hardware/boards/warehouse_v2/crosslab:build
  - script: build_axis_portal_v2
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/axis_portal_v2/fpga:build
      - hardware/boards/axis_portal_v2/crosslab:build
  - script: build_mole
    dependencies:
      - hardware/common/config-interface:build
      - hardware/common/spi-driver:build
      - hardware/boards/mole/fpga:build
      - hardware/boards/mole/crosslab:build
