variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: crosslab/development-container

default:
  before_script:
    - mkdir -p ~/.ssh/ && cp "$CI_SSH_KEY" ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cd "$PROJECT_DIR"
  after_script:
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/upload_badges.sh $CI_JOB_STATUS

.build:
  script:
    - wget https://img.shields.io/badge/build-passing-success?style=flat-square -O "badge_${CI_JOB_NAME//\//_}_success.svg"
    - wget https://img.shields.io/badge/build-failed-critical?style=flat-square -O "badge_${CI_JOB_NAME//\//_}_failed.svg"
    - ./scripts/build.sh
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh
  artifacts:
    paths:
      - $PROJECT_DIR/dist

.build-spec:
  script:
    - wget https://img.shields.io/badge/spec%20build-passing-success?style=flat-square -O "badge_${CI_JOB_NAME//\//_}_success.svg"
    - wget https://img.shields.io/badge/spec%20build-failed-critical?style=flat-square -O "badge_${CI_JOB_NAME//\//_}_failed.svg"
    - ./scripts/build.sh -s
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh
  artifacts:
    paths:
      - $PROJECT_DIR/dist
    
.lint:
  script:
    - wget https://img.shields.io/badge/linting-passing-success?style=flat-square -O "badge_${CI_JOB_NAME//\//_}_success.svg"
    - wget https://img.shields.io/badge/linting-failed-critical?style=flat-square -O "badge_${CI_JOB_NAME//\//_}_failed.svg"
    - ./scripts/lint.sh

.test:
  script:
    - wget https://img.shields.io/badge/tests-passing-success?style=flat-square -O "badge_${CI_JOB_NAME//\//_}_success.svg"
    - wget https://img.shields.io/badge/tests-failed-critical?style=flat-square -O "badge_${CI_JOB_NAME//\//_}_failed.svg"
    - ./scripts/test.sh

################################################################################
# Helper #######################################################################
################################################################################
> helper/tsdoc-theme build
> helper/openapi-codegeneration build
> helper/crosslab-typescript-addon build < helper/openapi-codegeneration:build

################################################################################
# Backend ######################################################################
################################################################################

> backend-services/auth build-spec
> backend-services/auth lint < backend-services/auth:build-spec

> backend-services/booking build-spec
> backend-services/booking lint < backend-services/booking:build-spec

> backend-services/device build-spec
> backend-services/device lint < backend-services/device:build-spec

> backend-services/experiment build-spec
> backend-services/experiment lint < backend-services/experiment:build-spec

> backend-services/federation build-spec
> backend-services/federation lint < backend-services/federation:build-spec

> backend-services/update build-spec
> backend-services/update lint < backend-services/update:build-spec


> backend-services/openapi build-spec < backend-services/auth:build-spec backend-services/booking:build-spec backend-services/device:build-spec backend-services/experiment:build-spec backend-services/federation:build-spec backend-services/update:build-spec
> backend-services/openapi lint < backend-services/openapi:build-spec backend-services/auth:lint backend-services/booking:lint backend-services/device:lint backend-services/experiment:lint backend-services/federation:lint backend-services/update:lint

################################################################################
# Clients ######################################################################
################################################################################
> clients/api/js build < backend-services/auth:build-spec backend-services/booking:build-spec backend-services/device:build-spec backend-services/experiment:build-spec backend-services/federation:build-spec backend-services/update:build-spec helper/crosslab-typescript-addon:build helper/tsdoc-theme:build helper/openapi-codegeneration:build

> clients/api/python build < backend-services/openapi:build-spec helper/openapi-codegeneration:build
> clients/api/python lint < clients/api/python:build
> clients/api/python test < clients/api/python:build

> clients/soa/python build < backend-services/openapi:build-spec helper/openapi-codegeneration:build clients/api/python:test
> clients/soa/python lint < clients/soa/python:build
> clients/soa/python test < clients/soa/python:build

# SOA Service ##################################################################

> clients/soa_services/electricalConnection/python build < clients/api/python:test clients/soa/python:test
> clients/soa_services/electricalConnection/python lint < clients/soa_services/electricalConnection/python:build
> clients/soa_services/electricalConnection/python test < clients/soa_services/electricalConnection/python:lint

################################################################################
# Hardware #####################################################################
################################################################################
hardware/os-rebuild-world:
  image: ghcr.io/siemens/kas/kas
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  timeout: 48h
  script:
    - cd hardware/os
    - mkdir -p ~/.ssh/ && cp "$CI_SSH_KEY" ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cp "$LOCAL_YML_NO_CACHE" local.yml && cp "$DEV_CRT" signing.crt.pem && cp "$DEV_KEY" signing.key.pem
    - ./scripts/build.sh -c -w --run_on_host
    - ./scripts/sync_sstate.sh -c
    - cd "$CI_BUILDS_DIR" && cd "$CI_PROJECT_DIR" && ./scripts/check_no_changes.sh