################################################################################
# Build Development Container ##################################################
################################################################################

helper/crosslab-development-container:
  - script: build -t crosslab-development-container:latest

helper/goldi-development-container:
  - script: build
    dependencies:
      - helper/crosslab-development-container:build

################################################################################
# Frontend Services ############################################################
################################################################################

frontend-services/config-tool:
  - script: build
#    dependencies:
#      - clients/api/js:build

frontend-services/experiment-control-panel:
  - script: build
 #   dependencies:
 #     - clients/api/js:build
 #     - clients/soa/js:build
 #     - clients/soa_services/electricalConnection/js:build
 #     - clients/soa_services/webcam/js:build
 #     - clients/soa_services/file/js:build

hardware/common/config-interface:
  - script: build
  - script: lint