stages:
  - build_backend 
  - build_frontend
  - test
  - deploy
  
build_job_backend:
  stage: build_backend
  script:
    - npm install --prefix NodeServer
  artifacts:
    when: on_success
    paths:
      - NodeServer/

build_job_frontend:
  stage: build_frontend
  script:
    - npm install --prefix WIDE_OLD/WIDE
    - npm run setup-all --prefix WIDE_OLD/WIDE
  artifacts:
    when: on_success
    paths:
      - WIDE_OLD/WIDE/dist/
     
test_job:
  stage: test
  script:
    - npm run test --prefix WIDE_OLD/WIDE
    - npm run test --prefix NodeServer

deploy-production_job:
  stage: deploy
  script:
    - ssh goldi-experimental "rm -rf /var/local/www/GOLDiWebsite/WIDE/*"
    - scp -r WIDE_OLD/WIDE/dist/* goldi-experimental:/var/local/www/GOLDiWebsite/WIDE/
    - ssh goldi-experimental "rm -rf /home/goldi/git/wide/NodeServer/*"
    - scp -r NodeServer/* goldi-experimental:/home/goldi/git/wide/NodeServer
    - ssh -t goldi-experimental "sudo npm run start --prefix /home/goldi/git/wide/NodeServer"
  only:
    - development
