FROM node:lts-bookworm AS build

WORKDIR /tmp/build

RUN apt update
RUN apt install -y build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3
RUN git clone https://github.com/microsoft/vscode.git -b 1.93.0

WORKDIR /tmp/build/vscode

RUN yarn
RUN yarn gulp vscode-web-min