#!/bin/sh

# cloud led green
/bin/echo none > /sys/class/leds/green\:cloud/trigger
/bin/echo 255 > /sys/class/leds/green\:cloud/brightness

/bin/echo none > /sys/class/leds/red\:cloud/trigger
/bin/echo 0 > /sys/class/leds/red\:cloud/brightness

# disable active led
/bin/echo none > /sys/class/leds/red\:active/trigger
/bin/echo 0 > /sys/class/leds/red\:active/brightness

/bin/echo none > /sys/class/leds/green\:active/trigger
/bin/echo 0 > /sys/class/leds/green\:active/brightness