image: ghcr.io/siemens/kas/kas

variables:
  GIT_CLEAN_FLAGS: -ffdx -e /build/

io-board:
  stage: build
  script:
    - sudo apt-get update && sudo apt-get install gettext-base
    - cat "$LOCAL_YML" | envsubst > "local.yml"
    - kas build kas.yml