image: ghcr.io/siemens/kas/kas

variables:
  GIT_CLEAN_FLAGS: -ffdx -e /build/

io-board:
  stage: build
  script:
    - cp "$CI_SSH_KEY" ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - sudo apt-get update && sudo apt-get install gettext-base
    - cat "$LOCAL_YML" | envsubst > "local.yml"
    - kas build kas.yml
    - rsync --rsync-path 'sudo rsync' -a --progress --chmod=755 build/sstate-cache/ admin@x56.theoinf.tu-ilmenau.de:/data/www/x56/share/sstate