image: ghcr.io/siemens/kas/kas

variables:
  GIT_CLEAN_FLAGS: -ffdx -e /build/

io-board:
  stage: build
  script:
    - mkdir -p ~/.ssh/
    - cp "$CI_SSH_KEY" ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - sudo apt-get update && sudo apt-get install gettext-base
    - cat "$LOCAL_YML" | envsubst > "local.yml"
    - kas build kas.yml
    - rsync -e "ssh -o StrictHostKeyChecking=no" --rsync-path 'sudo rsync' -a --progress --chmod=755 build/sstate-cache/ admin@x56.theoinf.tu-ilmenau.de:/data/www/x56/share/sstate
    - rsync -e "ssh -o StrictHostKeyChecking=no" --rsync-path 'sudo rsync' -a --progress --chmod=755 build/tmp/deploy/ipk/ admin@x56.theoinf.tu-ilmenau.de:/data/www/package/ipk-dev
    - rsync -e "ssh -o StrictHostKeyChecking=no" --rsync-path 'sudo rsync' -a --progress --chmod=755 -L build/tmp/deploy/images/io-board/goldi-*io-board.*raucb admin@x56.theoinf.tu-ilmenau.de:/data/www/x56/update
    - rsync -e "ssh -o StrictHostKeyChecking=no" --rsync-path 'sudo rsync' -a --progress --chmod=755 -L build/tmp/deploy/images/io-board/goldi-*io-board.wic* admin@x56.theoinf.tu-ilmenau.de:/data/www/x56/image