
 import "./test-a.ts"
 import "./test-button.ts"
 import "./automaton-button.ts"
 import "./my-element.ts"
 import "./changeNameButton.ts"
 import "./top-bar.ts"
 import "./graphViewer.ts"
 import "./mainRouterElement.ts"
 import "./operatorTestElement.ts"
 import "./SimulationElement.ts"
 import "./equationElement.ts"
 import "./transitionMatrixElement.ts"
 import "./bTest.ts"
 import "./side-bar.ts"
 import "./bezierSVG.ts"
 import "./generalTableElement.ts"
 import "./errorWindow.ts"
 import "./goldi-drop-menu.ts"
 import "./goldi-drop-menu-entry.ts"
 import "@material/mwc-checkbox"
 import "@material/mwc-list"
 import "@material/menu"
 import { classMap } from 'lit-html/directives/class-map'
 import { connect } from 'pwa-helpers';