image: $CI_REGISTRY/$ci_registry_group/buildimage:latest

build-test-docker-deploy-job:
  stage: build
  script:
    - npm install
    - npm run build:node
    - npm test
    - npm run build:docker

    - docker login -u $docker_hub_user -p $docker_hub_token
    - docker tag goldi2/web-frontend:latest goldi2/web-frontend:staging
    - docker rmi goldi2/web-frontend:latest
    - docker push goldi2/web-frontend:staging