image: $CI_REGISTRY/$ci_registry_group/buildimage:latest

build-test-docker-deploy-job:
  stage: build
  script:
    - npm install
    - npm run build:node
    - npm test
    - npm run build:docker

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag goldi2/web-frontend:latest goldi2/web-frontend:staging
    - docker rmi goldi2/web-frontend:latest
    - docker push goldi2/web-frontend:staging